document.writeln("");
document.writeln("    <header class=\'main-header\'>");
document.writeln("    <a href=\'#\' class=\'logo\'>");
document.writeln("       <span class=\'logo-lg\'><b>Pala</b>.com</span>");
document.writeln("    </a>");
document.writeln("    <nav class=\'navbar navbar-static-top\'>");
document.writeln("      <!-- Sidebar toggle button-->");
document.writeln("      <div class=\'navbar-custom-menu\'>");
document.writeln("        <ul class=\'nav navbar-nav\'>");
document.writeln("          <!-- User Account: style can be found in dropdown.less -->");
document.writeln("          <li class=\'dropdown user user-menu\'>");
document.writeln("            <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>");
document.writeln("             <img src=\'../../img/user2-160x160.jpg\' class=\'user-image\' alt=\'User Image\'>");
document.writeln("              <span class=\'hidden-xs\'>张三</span>");
document.writeln("            </a>");
document.writeln("            <ul class=\'dropdown-menu\'>");
document.writeln("              <!-- User image -->");
document.writeln("              <li class=\'user-header\'>");
document.writeln("                <img src=\'../../img/user2-160x160.jpg\' class=\'img-circle\' alt=\'User Image\'>");
document.writeln("              </li>");
document.writeln("              <!-- Menu Body -->");
document.writeln("            </ul>");
document.writeln("          </li>");
document.writeln("          <!-- Control Sidebar Toggle Button -->");
document.writeln("          <li>");
document.writeln("            <a href=\'#\' data-toggle=\'control-sidebar\'><i class=\'fa fa-gears\'></i></a>");
document.writeln("          </li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("    </nav>");
document.writeln("  </header>");
document.writeln("  <!-- Left side column. contains the logo and sidebar -->");
document.writeln("  <aside class=\'main-sidebar\'>");
document.writeln("    <!-- sidebar: style can be found in sidebar.less -->");
document.writeln("    <section class=\'sidebar\'>");
document.writeln("      <!-- Sidebar user panel -->");
document.writeln("      <div class=\'user-panel\'>");
document.writeln("        <div class=\'pull-left image\'>");
document.writeln("          <img src=\'../../img/user2-160x160.jpg\' class=\'img-circle\' alt=\'User Image\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'pull-left info\'>");
document.writeln("          <p>张三</p>");
document.writeln("          <a href=\'#\'><i class=\'fa fa-circle text-success\'></i>在线</a>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("      <!-- search form -->");
document.writeln("    ");
document.writeln("      <!-- /.search form -->");
document.writeln("      <!-- sidebar menu: : style can be found in sidebar.less -->");
document.writeln("    <ul class=\'sidebar-menu\' data-widget=\'tree\'>");
document.writeln("        <li class=\'header\'>MAIN NAVIGATION</li>");
document.writeln("        <li class=\'treeview\'>");
document.writeln("          <a href=\'#\'>");
document.writeln("            <i class=\'fa fa-pie-chart\'></i>");
document.writeln("            <span>基础配置</span>");
document.writeln("            <span class=\'pull-right-container\'>");
document.writeln("              <i class=\'fa fa-angle-left pull-right\'></i>");
document.writeln("            </span>");
document.writeln("          </a>");
document.writeln("            <ul class=\'treeview-menu\'>");
document.writeln("            <li><a href=\'../../tables/RoleManagement/roalmanager.html\'><i class=\'fa fa-circle-o\'></i> 角色管理</a></li>");
document.writeln("            <li><a href=\'../../tables/ResourceManagement/ziyuan.html\'><i class=\'fa fa-circle-o\'></i> 资源管理</a></li>");
document.writeln("            <li><a href=\'../../tables/UserManagement/yonghu.html\'><i class=\'fa fa-circle-o\'></i> 用户管理</a></li>");
document.writeln("            <li><a href=\'../../tables/ModuleManagement/mokuai.html\'><i class=\'fa fa-circle-o\'></i> 模块管理</a></li>");
document.writeln("            <li><a href=\'../../tables/ClassificationManagement/fenlei.html\'><i class=\'fa fa-circle-o\'></i> 分类管理</a></li>");
document.writeln("            <li><a href=\'../../tables/InstitutionalManagement/jigou.html\'><i class=\'fa fa-circle-o\'></i> 机构管理</a></li>");
document.writeln("            ");
document.writeln("            <li class=\'treeview\'>");
document.writeln("             <a href=\'#\'>");
document.writeln("            <i class=\'fa fa-plus\'></i>");
document.writeln("            <span>技能管理</span>");
document.writeln("          </a>");
document.writeln("          <ul class=\'treeview-menu\'>");
document.writeln("             <li><a href=\'../../tables/SkillsManagement/renyuanjineng.html\'><i class=\'fa fa-minus\'></i>人员技能维护</a></li>");
document.writeln("             <li><a href=\'../../tables/SkillsManagement/jineng.html\'><i class=\'fa fa-minus\'></i>系统技能维护</a></li>");
document.writeln("          </ul>");
document.writeln("        </li>");
document.writeln("");
document.writeln("            <li><a href=\'#\'><i class=\'fa fa-circle-o\'></i> 属性扩展</a></li>");
document.writeln("          </ul>");
document.writeln("        </li>");
document.writeln("        <li class=\'treeview\'>");
document.writeln("          <a href=\'#\'>");
document.writeln("            <i class=\'fa fa-laptop\'></i>");
document.writeln("            <span>其它</span>");
document.writeln("            <span class=\'pull-right-container\'>");
document.writeln("              <i class=\'fa fa-angle-left pull-right\'></i>");
document.writeln("            </span>");
document.writeln("          </a>");
document.writeln("          <ul class=\'treeview-menu\'>");
document.writeln("             <li><a href=\'#\'><i class=\'fa fa-circle-o\'></i> 监控</a></li>");
document.writeln("          </ul>");
document.writeln("        </li>");
document.writeln("    </section>");
document.writeln("  </aside>");